name: Debug

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build"
        required: true

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Determine version
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          VERSION=${{ github.event.inputs.tag }}
        else
          VERSION=${{ github.ref_name }}
        fi
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "version=${VERSION}"
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build release APKs
      env:
        VERSION_NAME: ${{ steps.version.outputs.version }}
      run: |
        ./gradlew assembleRelease
        mkdir release-apks
        cp client-app/build/outputs/apk/release/gnss-client-${VERSION_NAME}-release.apk release-apks/gnss-client-${VERSION_NAME}.apk
        cp server-app/build/outputs/apk/release/gnss-server-${VERSION_NAME}-release.apk release-apks/gnss-server-${VERSION_NAME}.apk
